import 'package:video_streaming/data/model/video_list_model.dart';

VideoListModel buildVideoListFromTemplate({
  required List<Result> videoResultList,
}){
  return VideoListModel(videoResultList.length, videoResultList,);
}

Result buildVideoResultFromTemplate({
  String wrapperType = '',
  String kind = '',
  int artistId = 1,
  int collectionId = 1,
  int trackId = 1,
  String artistName = '',
  String collectionName = '',
  String trackName = '',
  String collectionCensoredName = '',
  String trackCensoredName = '',
  String artistViewUrl = '',
  String collectionViewUrl = '',
  String trackViewUrl = '',
  String previewUrl = '',
  String artworkUrl30 = '',
  String artworkUrl60 = '',
  String artworkUrl100 = '',
  double collectionPrice = 0,
  double trackPrice = 0,
  String releaseDate = '',
  String collectionExplicitness = '',
  String trackExplicitness = '',
  int discCount = 0,
  int discNumber = 0,
  int trackCount = 0,
  int trackNumber = 0,
  int trackTimeMillis = 0,
  String country = '',
  String currency = '',
  String primaryGenreName = '',
}) {
  return Result(
    wrapperType,
    kind,
    artistId,
    collectionId,
    trackId,
    artistName,
    collectionName,
    trackName,
    collectionCensoredName,
    trackCensoredName,
    artistViewUrl,
    collectionViewUrl,
    trackViewUrl,
    previewUrl,
    artworkUrl30,
    artworkUrl60,
    artworkUrl100,
    collectionPrice,
    trackPrice,
    releaseDate,
    collectionExplicitness,
    trackExplicitness,
    discCount,
    discNumber,
    trackCount,
    trackNumber,
    trackTimeMillis,
    country,
    currency,
    primaryGenreName,
  );
}
